### ISSUE TITLE
Error in 1.18 / Update to 1.18

### ISSUE THREAD

**Issue by SlyyJacob** [Arthed-Plugins/WallJump#1]
Hey, I was wondering if it's possible to update the plugin to 1.18, please?
I've tried the 1.17 version in 1.18 but it errors out on startup:

```
[09:44:51 INFO]: Enabling WallJump v2.0.1
[09:44:51 ERROR]: Error occurred while enabling WallJump v2.0.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at me.arthed.walljump.utils.AntiCheatUtils.<init>(AntiCheatUtils.java:18) ~[WallJump-2.0.1.jar:?]
	at me.arthed.walljump.WallJump.onEnable(WallJump.java:82) ~[WallJump-2.0.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-53]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-53]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-53]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-53]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant me.arthed.walljump.utils.BukkitUtils.Version.V1_18
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at me.arthed.walljump.utils.BukkitUtils$Version.valueOf(BukkitUtils.java:44) ~[WallJump-2.0.1.jar:?]
	at me.arthed.walljump.utils.BukkitUtils.<clinit>(BukkitUtils.java:12) ~[WallJump-2.0.1.jar:?]
	... 13 more
[09:44:51 INFO]: Disabling WallJump v2.0.1

```

**Comment by Styro457** [comment]
Fixed in pre-release 2.0.2-beta.1

Proper release should also be out soon
